[General]
appearance=1
autosaveIntervalMinutes=2
copyAsImageTimeout=3
deletedDefaultMuds=Abandoned Realms, Carrion Fields, CoreMUD, Legends of the Jedi, Cleft of Dimensions, Accursed Lands, Fierymud, Reinos de Leyenda, Clessidra, StickMUD, Luminari, Midnight Sun 2, WoTMUD, Imperian, Aetolia, ZombieMUD, Realms of Despair, Mudren, Materia Magica, Aardwolf, Slothmud, God Wars II, BatMUD, Lusternia, 3Scapes, 3Kingdoms, Achaea, Avalon.de, MorgenGrauen, Multi-Users in Middle-earth
editorTextOptions=0
enableFullScreenMode=false
enableMultiViewMode=false
enableMuteAPI=false
enableMuteMCMP=false
enableMuteMSP=false
interfaceLanguage=en_US
mActionEditorSplitterState=@ByteArray()
mAliasEditorSplitterState=@ByteArray()
mKeyEditorSplitterState=@ByteArray()
mScriptEditorSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\0\x80\0\0\x3\x84\0\0\0\x64\x1\0\0\0\x5\x1\0\0\0\x2\0)
mTimerEditorSplitterState=@ByteArray()
mTriggerEditorSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1^\0\0\x3\x84\0\0\0\x64\x1\0\0\0\x5\x1\0\0\0\x2\0)
mVarEditorSplitterState=@ByteArray()
mainiconsize=3
maximized=true
menuBarVisibility=3
minLengthForSpellCheck=3
pos=@Point(0 0)
reportMapIssuesToConsole=false
script_editor_pos=@Point(0 0)
script_editor_size=@Size(740 891)
showIconsInMenus=1
showMenuBar=true
showToolbar=true
size=@Size(1492 891)
storePasswordsSecurely=true
tefoldericonsize=3
toolBarVisibility=3
