return {{[ [[triggers]] ] = {2},[ [[aliases]] ] = {3},},
{},
{[1] = {4},[2] = {5},[3] = {6},[4] = {7},[5] = {8},[6] = {9},},
{[1] = 1170,[2] = [[rhos1]],[3] = [[do n,n,n,n,w,w,w,n,n,w,w,n,n,n,w,n,w,n,w,n,w,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,e,e,e,e,e,e,e,path,privy,push walls, 5evade, climb out,out,path,w,w,w,w,s,w,s,w,s,s,w,s,s,s,s,s,s,s,s,s,s,s,s,s,s,s,e,s,s,s,e,s,s,e,s,s,e,e,s,e,s,s,e,s,e,e,s]],},
{[1] = 1171,[2] = [[riv1]],[3] = [[do nw,nw,w,w,nw,w,sw,nw,feel behind waterfall, 5evade, out,se,se,se,ne,se,e,e,e]],},
{[1] = 1172,[2] = [[riv2]],[3] = [[do 3e,2u,ring bell,5evade,d,3w]],},
{[1] = 1173,[2] = [[loth1]],[3] = [[do 20n,12e,path,climb chain,5evade,aft,aft,helm,enter hatch,5evade,climb up,5evade,deck,fore,fore,chain,path,12w,20s]],},
{[1] = 1174,[2] = [[loth2]],[3] = [[do w,s,e,s,5look waterfall,climb waterfall,15evade,out,n,w,n,e]],},
{[1] = 1175,[2] = [[thran1]],[3] = [[do 12n,16e,crawl behind shrub,5evade,out,16w,12s]],},
}