return {{[ [[Esker]] ] = {2},[ [[Qfm]] ] = {3},[ [[Zelindo]] ] = {4},[ [[Isadore]] ] = {5},[ [[Baern]] ] = {6},[ [[Alaran]] ] = {7},[ [[Keria]] ] = {8},[ [[Lunasik]] ] = {9},[ [[Auri]] ] = {10},[ [[Elleo]] ] = {11},[ [[Halen]] ] = {12},[ [[Rhoads]] ] = {13},[ [[Xaron]] ] = {14},[ [[Gleam]] ] = {15},[ [[Alkath]] ] = {16},[ [[Lunner]] ] = {17},[ [[Ahri]] ] = {18},[ [[Nalthic]] ] = {19},[ [[Cori]] ] = {20},[ [[Fingondor]] ] = {21},[ [[Montog]] ] = {22},[ [[Gendor]] ] = {23},[ [[Razer]] ] = {24},[ [[Jaed]] ] = {25},[ [[Ethereal]] ] = {26},[ [[Sprotticus]] ] = {27},[ [[Egypt]] ] = {28},[ [[Ishiv]] ] = {29},[ [[Zickle]] ] = {30},[ [[Nyssa]] ] = {31},[ [[Argazi]] ] = {32},[ [[Carath]] ] = {33},},
{[1] = [[Quality]],[2] = [[Vazroth]],[3] = [[Waleran]],[4] = [[Etrius]],},
{[1] = [[Ghazi]],},
{[1] = [[Theodrek]],},
{[1] = [[Verikal]],},
{[1] = [[Mekhennen]],[2] = [[Timbia]],[3] = [[Zakral]],},
{[1] = [[Dizm]],},
{[1] = [[Dedfish]],},
{[1] = [[Deadlok]],[2] = [[Deathlok]],[3] = [[Kysanul]],},
{[1] = [[Olostar]],[2] = [[Terias]],[3] = [[Kadaver]],[4] = [[Adophson]],[5] = [[Alycone]],},
{[1] = [[Gerrard]],[2] = [[Rian]],},
{[1] = [[Shartan]],},
{[1] = [[Fingolfin]],},
{[1] = [[Wyvern]],},
{[1] = [[Byron]],[2] = [[Chosen]],[3] = [[Beam]],[4] = [[Toto]],},
{[1] = [[Arnt]],[2] = [[Petrus]],[3] = [[Bror]],[4] = [[Bernt]],[5] = [[Brute]],[6] = [[Dolph]],},
{[1] = [[Notus]],[2] = [[Miliken]],},
{[1] = [[Raiko]],},
{[1] = [[Reaper]],},
{[1] = [[Khikril]],[2] = [[Asgeirr]],[3] = [[Ryuk]],[4] = [[Thumlin]],[5] = [[Ingemar]],},
{[1] = [[Ciryatur]],},
{[1] = [[Snuff]],[2] = [[Daxx]],},
{[1] = [[Vauglir]],},
{[1] = [[Aethuin]],},
{[1] = [[Aether]],},
{[1] = [[Aginor]],[2] = [[Demandred]],},
{[1] = [[Latty]],},
{[1] = [[Mathew]],[2] = [[Akh]],},
{[1] = [[Vazaroth]],},
{[1] = [[Cameron]],},
{[1] = [[Shoshana]],[2] = [[Ainsley]],[3] = [[Siobhan]],[4] = [[Esther]],},
{[1] = [[Lotus]],},
{[1] = [[Akbar]],},
}