return {{[1] = {2},[2] = {3},[3] = {4},[4] = {5},[5] = {6},[6] = {7},[7] = {8},[8] = {9},[9] = {10},[10] = {11},[11] = {12},[12] = {13},[13] = {14},[14] = {15},[15] = {16},[16] = {17},[20] = {18},[17] = {19},[21] = {20},[18] = {21},[22] = {22},[19] = {23},[23] = {24},},
{[ [[exit]] ] = [[east]],[ [[room]] ] = [[1224]],[ [[maxAlign]] ] = [[Demonic]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[knock on gate]],[ [[room]] ] = [[1194]],[ [[maxAlign]] ] = [[Demonic]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[gate]],[ [[room]] ] = [[23029]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Heroic]],},
{[ [[exit]] ] = [[knock on door]],[ [[room]] ] = [[23047]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Angelic]],},
{[ [[exit]] ] = [[gate]],[ [[room]] ] = [[22907]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Immoral]],},
{[ [[exit]] ] = [[south]],[ [[room]] ] = [[20914]],[ [[maxAlign]] ] = [[Immoral]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[north]],[ [[room]] ] = [[433]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Impartial]],},
{[ [[exit]] ] = [[2knock on gates]],[ [[room]] ] = [[55803]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[2knock on gates]],[ [[room]] ] = [[20474]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[join caravan]],[ [[room]] ] = [[29509]],[ [[maxAlign]] ] = [[Evilrace]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[enter]],[ [[room]] ] = [[2810]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Servant]],},
{[ [[exit]] ] = [[knock on gates]],[ [[room]] ] = [[173]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Shadowspawn of Mordor]],},
{[ [[exit]] ] = [[east]],[ [[room]] ] = [[60495]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[2knock on gates]],[ [[room]] ] = [[24288]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[2knock on gates]],[ [[room]] ] = [[62013]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[east]],[ [[room]] ] = [[62443]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[northwest]],[ [[room]] ] = [[653]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Servant]],},
{[ [[exit]] ] = [[gate]],[ [[room]] ] = [[62036]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[north]],[ [[room]] ] = [[63773]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[west]],[ [[room]] ] = [[1484]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Servant]],},
{[ [[exit]] ] = [[traverse wreckage]],[ [[room]] ] = [[65355]],[ [[maxAlign]] ] = [[Servant]],[ [[minAlign]] ] = [[Evilrace]],},
{[ [[exit]] ] = [[west]],[ [[room]] ] = [[1426]],[ [[maxAlign]] ] = [[Hand of Eru]],[ [[minAlign]] ] = [[Servant]],},
{[ [[exit]] ] = [[east]],[ [[room]] ] = [[15005]],[ [[maxAlign]] ] = [[Demonic]],[ [[minAlign]] ] = [[Evilrace]],},
}