return {{[1] = {2},[2] = {3},[3] = {4},[4] = {5},[5] = {6},[6] = {7},[7] = {8},[8] = {9},[9] = {10},[10] = {11},[11] = {12},[12] = {13},[13] = {14},[14] = {15},[15] = {16},[16] = {17},[17] = {18},[18] = {19},[19] = {20},[20] = {21},[21] = {22},[22] = {23},[23] = {24},[24] = {25},[25] = {26},[26] = {27},[27] = {28},[28] = {29},[29] = {30},[30] = {31},[31] = {32},[32] = {33},[33] = {34},[34] = {35},[35] = {36},[36] = {37},[37] = {38},[38] = {39},[39] = {40},[40] = {41},[41] = {42},[42] = {43},[43] = {44},[44] = {45},[45] = {46},[46] = {47},[47] = {48},[48] = {49},[49] = {50},[50] = {51},[51] = {52},[52] = {53},[53] = {54},[54] = {55},[55] = {56},[56] = {57},[57] = {58},[58] = {59},[59] = {60},[60] = {61},[61] = {62},[62] = {63},[63] = {64},[64] = {65},[65] = {66},[66] = {67},[67] = {68},[68] = {69},[69] = {70},[70] = {71},[71] = {72},[72] = {73},[73] = {74},[74] = {75},[75] = {76},[76] = {77},[77] = {78},[78] = {79},[79] = {80},[80] = {81},[81] = {82},[82] = {83},[83] = {84},[84] = {85},[85] = {86},[86] = {87},[87] = {88},[88] = {89},[89] = {90},[90] = {91},[91] = {92},[92] = {93},[93] = {94},[94] = {95},[95] = {96},[96] = {97},[97] = {98},[98] = {99},[99] = {100},[100] = {101},[101] = {102},[102] = {103},[103] = {104},[104] = {105},[105] = {106},[106] = {107},[107] = {108},[108] = {109},[109] = {110},[110] = {111},[111] = {112},[112] = {113},[113] = {114},[114] = {115},[115] = {116},[116] = {117},[117] = {118},[118] = {119},[119] = {120},[120] = {121},[121] = {122},[122] = {123},[123] = {124},[124] = {125},[125] = {126},[126] = {127},[127] = {128},[128] = {129},[129] = {130},},
{[ [[exits]] ] = [[path east south west]],[ [[roomName]] ] = [[Clearing]],[ [[newExits]] ] = [[path east south west down]],[ [[newName]] ] = [[Clearing]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[Near a guard flet]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Lothlórien]],},
{[ [[exits]] ] = [[north east south west]],[ [[roomName]] ] = [[An area with some soft ground]],[ [[newExits]] ] = [[north east south west down]],[ [[newName]] ] = [[An area with some soft ground]],},
{[ [[exits]] ] = [[northeast]],[ [[roomName]] ] = [[A small passageway]],[ [[newExits]] ] = [[northeast out]],[ [[newName]] ] = [[A small passageway]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[The shop]],[ [[newExits]] ] = [[south down]],[ [[newName]] ] = [[The shop]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[The bandit leader's shack]],[ [[newExits]] ] = [[south down]],[ [[newName]] ] = [[The bandit leader's shack]],},
{[ [[exits]] ] = [[north east]],[ [[roomName]] ] = [[Bree general store]],[ [[newExits]] ] = [[north east down]],[ [[newName]] ] = [[Bree general store]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A fork]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[An intersection]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dead-end]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A tunnel]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[East end of the main tunnel]],[ [[newExits]] ] = [[east west]],[ [[newName]] ] = [[East end of the main tunnel]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[The entrance to Shelob's lair]],[ [[newExits]] ] = [[east west]],[ [[newName]] ] = [[The entrance to Shelob's lair]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dark stairway]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[An ominous stairway]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dimly lit stairway]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[An ominous stairway]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[The raucous great hall]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The silent great hall]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A noisy meeting chamber]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A quiet meeting chamber]],},
{[ [[exits]] ] = [[east west]],[ [[roomName]] ] = [[A small, natural cave]],[ [[newExits]] ] = [[east south west]],[ [[newName]] ] = [[A small, natural cave]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A deep trench, filled with smoke and ruin]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A trench full of flames and smoke]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[An oasis in the desert]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The Harad Desert]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[The great hall in utter chaos]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The silent great hall]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dim meeting chamber]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A quiet meeting chamber]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A spiked pit]],[ [[newExits]] ] = [[west]],[ [[newName]] ] = [[A spiked pit]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A very quiet meeting chamber]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A quiet meeting chamber]],},
{[ [[exits]] ] = [[north east south]],[ [[roomName]] ] = [[A less used side road of Archet]],[ [[newExits]] ] = [[north east south west]],[ [[newName]] ] = [[A less used side road of Archet]],},
{[ [[exits]] ] = [[north up southwest]],[ [[roomName]] ] = [[A dimly lit inner chamber]],[ [[newExits]] ] = [[north up down southwest]],[ [[newName]] ] = [[A dimly lit inner chamber]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[A dead end]],[ [[newExits]] ] = [[south]],[ [[newName]] ] = [[A small cavern]],},
{[ [[exits]] ] = [[north]],[ [[roomName]] ] = [[A small house]],[ [[newExits]] ] = [[north down]],[ [[newName]] ] = [[A small house]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A bustling dining room]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A dining hall bathed in a dim yellow glow]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dimly lit tunnel]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A well lit tunnel]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A cold tunnel]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A well lit tunnel]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dark tunnel]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A well lit tunnel]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[An empty dining hall]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A dining hall bathed in a dim yellow glow]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[An empty, dark dining hall]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A dining hall bathed in a dim yellow glow]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A bustling meeting chamber]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A quiet meeting chamber]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A dining hall in the midst of lunch-time madness]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A dining hall bathed in a dim yellow glow]],},
{[ [[exits]] ] = [[out]],[ [[roomName]] ] = [[An extremely clean laboratory]],[ [[newExits]] ] = [[out]],[ [[newName]] ] = [[A messy laboratory]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A collapsed basement]],[ [[newExits]] ] = [[northeast northwest]],[ [[newName]] ] = [[A collapsed basement]],},
{[ [[exits]] ] = [[east southwest tent]],[ [[roomName]] ] = [[A ranger's campsite]],[ [[newExits]] ] = [[east southwest north tent]],[ [[newName]] ] = [[A ranger's campsite]],},
{[ [[exits]] ] = [[northeast]],[ [[roomName]] ] = [[A wooded riverbank]],[ [[newExits]] ] = [[northeast west]],[ [[newName]] ] = [[A wooded riverbank]],},
{[ [[exits]] ] = [[west east]],[ [[roomName]] ] = [[In a gloomy forest]],[ [[newExits]] ] = [[west east north]],[ [[newName]] ] = [[In a gloomy forest]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[The barracks of Gundabad]],[ [[newExits]] ] = [[east west]],[ [[newName]] ] = [[The barracks of Gundabad]],},
{[ [[exits]] ] = [[north]],[ [[roomName]] ] = [[The barracks of Gundabad]],[ [[newExits]] ] = [[north west]],[ [[newName]] ] = [[The barracks of Gundabad]],},
{[ [[exits]] ] = [[north south]],[ [[roomName]] ] = [[A small smithy]],[ [[newExits]] ] = [[north south east]],[ [[newName]] ] = [[A small smithy]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[A fireplace surrounded by snoring variags]],[ [[newExits]] ] = [[west]],[ [[newName]] ] = [[A festive fireplace]],},
{[ [[exits]] ] = [[hole out]],[ [[roomName]] ] = [[The lowest floor of the tower]],[ [[newExits]] ] = [[hole up out]],[ [[newName]] ] = [[The lowest floor of the tower]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A raided caravan]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The Harad Desert]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[A refuse-choked lookout post]],[ [[newExits]] ] = [[north south]],[ [[newName]] ] = [[A refuse-choked lookout post]],},
{[ [[exits]] ] = [[west south]],[ [[roomName]] ] = [[Troll lair]],[ [[newExits]] ] = [[north west south]],[ [[newName]] ] = [[Troll lair]],},
{[ [[exits]] ] = [[southeast]],[ [[roomName]] ] = [[A dead end]],[ [[newExits]] ] = [[chamber southeast]],[ [[newName]] ] = [[A well lit tunnel]],},
{[ [[exits]] ] = [[out]],[ [[roomName]] ] = [[Inside a large cavern]],[ [[newExits]] ] = [[west out]],[ [[newName]] ] = [[Inside a large cavern]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[A dark cave with an evil air]],[ [[newExits]] ] = [[east north]],[ [[newName]] ] = [[A dark cave with an evil air]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[A small valley]],[ [[newExits]] ] = [[west north]],[ [[newName]] ] = [[A small valley]],},
{[ [[exits]] ] = [[west south]],[ [[roomName]] ] = [[A bedroom]],[ [[newExits]] ] = [[west south east]],[ [[newName]] ] = [[A bedroom]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[A secret passage]],[ [[newExits]] ] = [[west south]],[ [[newName]] ] = [[A secret passage]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[A secret passage]],[ [[newExits]] ] = [[south west]],[ [[newName]] ] = [[A secret passage]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[Inside a house]],[ [[newExits]] ] = [[west down]],[ [[newName]] ] = [[Inside a house]],},
{[ [[exits]] ] = [[north south]],[ [[roomName]] ] = [[Atop the barrow of Haudh in Gwanur]],[ [[newExits]] ] = [[north down south]],[ [[newName]] ] = [[Atop the barrow of Haudh in Gwanur]],},
{[ [[exits]] ] = [[north northwest west]],[ [[roomName]] ] = [[Keep of Dol Amroth Castle]],[ [[newExits]] ] = [[north northwest west down]],[ [[newName]] ] = [[Keep of Dol Amroth Castle]],},
{[ [[exits]] ] = [[north southeast]],[ [[roomName]] ] = [[Inside a dry gulch]],[ [[newExits]] ] = [[north southeast east]],[ [[newName]] ] = [[Inside a dry gulch]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A spiked pit]],[ [[newExits]] ] = [[west]],[ [[newName]] ] = [[A spiked pit]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[The great hall in a disarray]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The silent great hall]],},
{[ [[exits]] ] = [[east southeast northeast west]],[ [[roomName]] ] = [[A warm meeting chamber]],[ [[newExits]] ] = [[east southeast northeast west]],[ [[newName]] ] = [[A quiet meeting chamber]],},
{[ [[exits]] ] = [[down up]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[down northeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[down east]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[down southeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[northwest up]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[northwest northeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[northwest east]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[northwest southeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[west up]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[west northeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[west east]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[west southeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[southwest up]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[southwest northeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[southwest east]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[southwest southeast]],[ [[roomName]] ] = [[A set of long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[A set of long winding stairs]],},
{[ [[exits]] ] = [[down east]],[ [[roomName]] ] = [[The top of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The top of some long winding stairs]],},
{[ [[exits]] ] = [[northwest east]],[ [[roomName]] ] = [[The top of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The top of some long winding stairs]],},
{[ [[exits]] ] = [[west east]],[ [[roomName]] ] = [[The top of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The top of some long winding stairs]],},
{[ [[exits]] ] = [[southwest east]],[ [[roomName]] ] = [[The top of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The top of some long winding stairs]],},
{[ [[exits]] ] = [[down up]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[down northeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[down east]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[down southeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[northwest up]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[northwest northeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[northwest east]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[northwest southeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[west up]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[west northeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[west east]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[west southeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[southwest up]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[southwest northeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[southwest east]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[southwest southeast]],[ [[roomName]] ] = [[The bottom of some long winding stairs]],[ [[newExits]] ] = [[northwest west southwest northeast east southeast up down]],[ [[newName]] ] = [[The bottom of some long winding stairs]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[Deeper in the cavern]],[ [[newExits]] ] = [[south up]],[ [[newName]] ] = [[Deeper in the cavern]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[The bedroom]],[ [[newExits]] ] = [[east west]],[ [[newName]] ] = [[The bedroom]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A poor boatman's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A council member's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A wine maker's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A curmudgeon's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A widow's plain home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A poor boatmaker's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A poor fisherman's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A house smelling of death]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A merchant's home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[south]],[ [[roomName]] ] = [[A storage room]],[ [[newExits]] ] = [[south down]],[ [[newName]] ] = [[A storage room]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[The Great Bridge of Laketown]],[ [[newExits]] ] = [[west east]],[ [[newName]] ] = [[The Great Bridge of Laketown]],},
{[ [[exits]] ] = [[north east south]],[ [[roomName]] ] = [[Near the Great Bridge and the Gate to Esgaroth]],[ [[newExits]] ] = [[north east south west]],[ [[newName]] ] = [[Near the Great Bridge and the Gate to Esgaroth]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[The Brandybuck Great Hall]],[ [[newExits]] ] = [[west south]],[ [[newName]] ] = [[The Brandybuck Great Hall]],},
{[ [[exits]] ] = [[west]],[ [[roomName]] ] = [[The Master's Sleeping Chambers]],[ [[newExits]] ] = [[north west]],[ [[newName]] ] = [[The Master's Sleeping Chambers]],},
{[ [[exits]] ] = [[east]],[ [[roomName]] ] = [[The Kitchen]],[ [[newExits]] ] = [[east down]],[ [[newName]] ] = [[The Kitchen]],},
{[ [[exits]] ] = [[second wagon north east west accountant wagon]],[ [[roomName]] ] = [[A destroyed caravan]],[ [[newExits]] ] = [[second wagon north east west accountant wagon south]],[ [[newName]] ] = [[A destroyed caravan]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A cluttered home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Druwaur home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A warm home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Druwaur home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[An abandoned hut]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Druwaur home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[An unwelcoming home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Druwaur home]],},
{[ [[exits]] ] = [[north east south]],[ [[roomName]] ] = [[Stonewain Valley]],[ [[newExits]] ] = [[north east south west]],[ [[newName]] ] = [[Stonewain Valley]],},
{[ [[exits]] ] = [[east west]],[ [[roomName]] ] = [[A natural spring]],[ [[newExits]] ] = [[northwest north southwest south southeast]],[ [[newName]] ] = [[A natural spring]],},
{[ [[exits]] ] = [[southeast]],[ [[roomName]] ] = [[A decent looking cellar]],[ [[newExits]] ] = [[west southeast]],[ [[newName]] ] = [[A decent looking cellar]],},
{[ [[exits]] ] = [[back]],[ [[roomName]] ] = [[On-board a small sunken ship]],[ [[newExits]] ] = [[back down]],[ [[newName]] ] = [[On-board a small sunken ship]],},
{[ [[exits]] ] = [[down]],[ [[roomName]] ] = [[Tower summit]],[ [[newExits]] ] = [[down up]],[ [[newName]] ] = [[Tower summit]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[Palantir room]],[ [[newExits]] ] = [[down]],[ [[newName]] ] = [[Palantir room]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A messy home]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[Esgaroth home]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[A small cavern at the end of a tunnel]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[A dead end]],},
{[ [[exits]] ] = [[]],[ [[roomName]] ] = [[The sombre great hall]],[ [[newExits]] ] = [[]],[ [[newName]] ] = [[The silent great hall]],},
{[ [[exits]] ] = [[down east west]],[ [[roomName]] ] = [[An elegant family room]],[ [[newExits]] ] = [[east west north down]],[ [[newName]] ] = [[An elegant family room]],},
}