return {{[ [[warrior]] ] = {2},[ [[tradeskill]] ] = {3},[ [[civilian]] ] = {4},[ [[minion]] ] = {5},[ [[sniffer]] ] = {6},[ [[necromancer]] ] = {7},[ [[rider]] ] = {8},[ [[archer]] ] = {9},[ [[thief]] ] = {10},[ [[wizard]] ] = {11},[ [[ranger]] ] = {12},[ [[language]] ] = {13},[ [[assassin]] ] = {14},},
{[1] = {15},[2] = {16},[3] = {17},[4] = {18},[5] = {19},[6] = {20},[7] = {21},[8] = {22},[9] = {23},[10] = {24},[11] = {25},[12] = {26},[13] = {27},[14] = {28},[15] = {29},[16] = {30},},
{},
{[1] = {31},[2] = {32},[3] = {33},[4] = {34},[5] = {35},[6] = {36},[7] = {37},[8] = {38},},
{},
{[1] = {39},[2] = {40},[3] = {41},[4] = {42},},
{[1] = {43},[2] = {44},[3] = {45},[4] = {46},[5] = {47},},
{[1] = {48},[2] = {49},[3] = {50},[4] = {51},[5] = {52},[6] = {53},[7] = {54},},
{[1] = {55},[2] = {56},[3] = {57},[4] = {58},[5] = {59},[6] = {60},[7] = {61},[8] = {62},[9] = {63},[10] = {64},[11] = {65},[12] = {66},},
{[1] = {67},[2] = {68},[3] = {69},[4] = {70},[5] = {71},[6] = {72},[7] = {73},},
{[1] = {74},[2] = {75},[3] = {76},[4] = {77},[5] = {78},[6] = {79},},
{[1] = {80},[2] = {81},[3] = {82},[4] = {83},[5] = {84},[6] = {85},[7] = {86},[8] = {87},[9] = {88},},
{[1] = {89},[2] = {90},[3] = {91},[4] = {92},[5] = {93},[6] = {94},[7] = {95},[8] = {96},[9] = {97},[10] = {98},[11] = {99},[12] = {100},[13] = {101},},
{[1] = {102},[2] = {103},[3] = {104},[4] = {105},[5] = {106},[6] = {107},[7] = {108},[8] = {109},},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, constitution, attack, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Scalus]],[ [[area]] ] = [[Bywater]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, aim, constitution, attack, defense, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Buckram Peary]],[ [[area]] ] = [[Bree]],},
{[ [[affinity]] ] = [[dwarves]],[ [[skills]] ] = [[tactics, constitution, attack, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Filo]],[ [[area]] ] = [[Belegost]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, constitution, attack, defense, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Fiskin]],[ [[area]] ] = [[Blue Mountains]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, fire building, combat arms, constitution, attack, blocking, dodge, tactics, strength, battle instincts]],[ [[name]] ] = [[Kisha]],[ [[area]] ] = [[Adornas]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, constitution, attack, defense, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Zhertrhashk]],[ [[area]] ] = [[Azmaroth]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, constitution, attack, defense, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Sufyan]],[ [[area]] ] = [[Easterling Refugee Camp]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[combat arms]],[ [[name]] ] = [[Vitak]],[ [[area]] ] = [[Outpost]],},
{[ [[affinity]] ] = [[evil men]],[ [[skills]] ] = [[combat arms, blocking, tactics, battle instincts]],[ [[name]] ] = [[Kurak]],[ [[area]] ] = [[Mirkwood]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[combat arms]],[ [[name]] ] = [[Kheligan]],[ [[area]] ] = [[Near Harad]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, aim, coordination, constitution, attack, combat arms, strength]],[ [[name]] ] = [[Savareth]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[dodge, coordination, attack, agility, blocking]],[ [[name]] ] = [[Iephos]],[ [[area]] ] = [[Linhir]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[dodge, tactics, defense, constitution, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Warrior]],[ [[area]] ] = [[Pelargir]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, coordination, combat arms, strength, awareness, battle instincts, blocking]],[ [[name]] ] = [[Devac]],[ [[area]] ] = [[Esgaroth]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[concentration, coordination, awareness, battle instincts]],[ [[name]] ] = [[Heder]],[ [[area]] ] = [[MT]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tactics, constitution, defense, attack, combat arms, strength, battle instincts, blocking]],[ [[name]] ] = [[Arthad]],[ [[area]] ] = [[MT]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fire building, combat arms, defense, locksmith, awareness, strength]],[ [[name]] ] = [[Falron]],[ [[area]] ] = [[Staddle]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma]],[ [[name]] ] = [[Trelia]],[ [[area]] ] = [[Grey Havens]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fire building]],[ [[name]] ] = [[Sheavener]],[ [[area]] ] = [[Outside Belegost]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fire building]],[ [[name]] ] = [[Anslem]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fire building]],[ [[name]] ] = [[Flegein]],[ [[area]] ] = [[Druwaur]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, intuition, constitution, attack, strength, awareness]],[ [[name]] ] = [[Tarlyn]],[ [[area]] ] = [[Framsburg]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, awareness]],[ [[name]] ] = [[Page]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, intelligence, awareness]],[ [[name]] ] = [[Councilmember]],[ [[area]] ] = [[Pelargir]],},
{[ [[affinity]] ] = [[uruk]],[ [[skills]] ] = [[wilderness, prowling, coordination, tracking, butchery, agility]],[ [[name]] ] = [[Girak]],[ [[area]] ] = [[Turseg]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[prowling, coordination, attack, agility, butchery, dodge, aim, tracking, evasion, deception, strength]],[ [[name]] ] = [[Hirdali'Qata]],[ [[area]] ] = [[Khemnahr]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[wilderness, butchery]],[ [[name]] ] = [[Rahmet]],[ [[area]] ] = [[Outpost]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[wilderness, prowling, tracking, butchery, evasion, intuition]],[ [[name]] ] = [[Haashim]],[ [[area]] ] = [[Umbar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[warp magic, defense, charisma, aim, intelligence, will, 6th sense]],[ [[name]] ] = [[Morgan]],[ [[area]] ] = [[Azrakadar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, dodge, warp magic, aim, intelligence, necromancy, agility, will, 6th sense]],[ [[name]] ] = [[Tezar]],[ [[area]] ] = [[Telshar]],},
{[ [[affinity]] ] = [[numenorean necromancer]],[ [[skills]] ] = [[6th sense, necromancy, will, warp magic, defense, aim, dodge, attack, awareness]],[ [[name]] ] = [[Gireth]],[ [[area]] ] = [[Asturasartes]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[warp magic, necromancy, fire building, defense, charisma, aim, intelligence, will, 6th sense]],[ [[name]] ] = [[Alazif]],[ [[area]] ] = [[Tarzhayan]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[resist magic]],[ [[name]] ] = [[Mishak]],[ [[area]] ] = [[East of Dry Lake]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[defense, taming, agility, awareness, balance, charisma, aim, motivation, intelligence, riding, mounted combat]],[ [[name]] ] = [[Leiff]],[ [[area]] ] = [[Adornas]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, aim, motivation, coordination, riding, taming, balance, mounted combat]],[ [[name]] ] = [[Gliell]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[motivation, aim, coordination, constitution, defense, agility, taming, mounted combat, balance]],[ [[name]] ] = [[Ingbor'tani]],[ [[area]] ] = [[Telshar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[constitution, attack, defense, combat arms, agility, charisma, dodge, aim, riding]],[ [[name]] ] = [[Bogar]],[ [[area]] ] = [[Asubuhi]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[motivation, taming, mounted combat, balance]],[ [[name]] ] = [[Grilos]],[ [[area]] ] = [[Southeast of Morgulduin]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[taming, balance, motivation, mounted combat]],[ [[name]] ] = [[Cyros]],[ [[area]] ] = [[Outpost]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, defense, constitution, agility, balance, motivation, riding, strength, mounted combat]],[ [[name]] ] = [[Rengel]],[ [[area]] ] = [[Edoras]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, coordination, agility, awareness, positioning, aim, deflecting, archery]],[ [[name]] ] = [[Girithron]],[ [[area]] ] = [[Grey Havens]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[aim, deflecting, defense, agility, awareness]],[ [[name]] ] = [[Eldaid]],[ [[area]] ] = [[Adornas]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, defense, agility]],[ [[name]] ] = [[Beechbone]],[ [[area]] ] = [[Michel Delving]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, coordination, defense, agility, awareness, positioning, aim, deflecting, archery]],[ [[name]] ] = [[Soronhen]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, coordination, agility, awareness, positioning, aim, deflecting, archery]],[ [[name]] ] = [[Aldred]],[ [[area]] ] = [[Druwaith Iaur]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[aim, deflecting, defense, agility, awareness]],[ [[name]] ] = [[Nahzkag]],[ [[area]] ] = [[Turseg]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[archery]],[ [[name]] ] = [[Tarrik]],[ [[area]] ] = [[Southeast of Morgulduin]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, coordination, defense, agility, positioning, deflecting, archery]],[ [[name]] ] = [[Haldir]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, coordination, defense, constitution, agility, positioning, deflecting, archery, strength]],[ [[name]] ] = [[Eother]],[ [[area]] ] = [[Edoras]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[aim, intelligence, constitution, defense, awareness]],[ [[name]] ] = [[Serith]],[ [[area]] ] = [[Linhir]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[fletching, attack, agility, positioning, aim, deflecting, intelligence, archery]],[ [[name]] ] = [[Archer]],[ [[area]] ] = [[Pelargir]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[aim, agility]],[ [[name]] ] = [[Cubeleg]],[ [[area]] ] = [[Maegon's Camp]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[nimbleness, coordination, defense, locksmith, agility, theft, stealth, intelligence, evasion]],[ [[name]] ] = [[Batlin]],[ [[area]] ] = [[Bywater]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[nimbleness, coordination, locksmith, agility, theft, dodge, stealth, evasion]],[ [[name]] ] = [[Halda]],[ [[area]] ] = [[Michel Delving]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[nimbleness, coordination, locksmith, agility, theft, dodge, stealth, evasion]],[ [[name]] ] = [[Tariq]],[ [[area]] ] = [[Easterling Refugee Camp]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[nimbleness]],[ [[name]] ] = [[Ariashal]],[ [[area]] ] = [[Umbar]],},
{[ [[affinity]] ] = [[thieves]],[ [[skills]] ] = [[nimbleness, coordination, defense, locksmith, agility, theft, stealth, intelligence]],[ [[name]] ] = [[Kimlo]],[ [[area]] ] = [[Thranduils]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[nimbleness, coordination, locksmith, agility, theft, awareness, dodge, stealth, aim]],[ [[name]] ] = [[Yevin]],[ [[area]] ] = [[Dale]],},
{[ [[affinity]] ] = [[thief]],[ [[skills]] ] = [[stealth, nimbleness, locksmith, agility, awareness, theft]],[ [[name]] ] = [[Scrom]],[ [[area]] ] = [[Pelargir]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[concentration, control magic, agility, awareness, dodge, resist magic, intelligence, 6th sense]],[ [[name]] ] = [[Luinil]],[ [[area]] ] = [[Grey Havens]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[concentration, resist magic, intelligence, control magic, 6th sense, awareness]],[ [[name]] ] = [[Merlac]],[ [[area]] ] = [[White Tower]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, concentration, resist magic, coordination, intelligence, control magic, 6th sense]],[ [[name]] ] = [[Eluhen]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[concentration, resist magic, control magic, 6th sense]],[ [[name]] ] = [[A large pedestal]],[ [[area]] ] = [[Thranduils]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[intelligence, agility, awareness]],[ [[name]] ] = [[Dawyin]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[concentration, control magic, agility, awareness, dodge, wilderness, resist magic, intelligence]],[ [[name]] ] = [[Aldwin]],[ [[area]] ] = [[Calembel]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, nature's grace, wilderness, intuition, fire building, riding, constitution, attack, nature's lore, tracking]],[ [[name]] ] = [[Aravir]],[ [[area]] ] = [[Bree]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, nature's grace, wilderness, intuition, aim, defense, agility, nature's lore, tracking]],[ [[name]] ] = [[Ramil]],[ [[area]] ] = [[Grey Havens]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[intuition, wilderness, nature's grace, coordination, constitution, attack, nature's lore, tracking]],[ [[name]] ] = [[Andavant]],[ [[area]] ] = [[Outside Annuminas]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[intuition, wilderness, nature's grace, intelligence, constitution, attack, nature's lore, tracking]],[ [[name]] ] = [[Hannonyl]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[rangers]],[ [[skills]] ] = [[dodge, intuition, fire building, defense, constitution, agility, awareness]],[ [[name]] ] = [[Old wise man]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[intuition, dodge, charisma, wilderness, concentration, resist magic, intelligence, riding, nature's lore, awareness]],[ [[name]] ] = [[Radagast]],[ [[area]] ] = [[Rhosgobel]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, nature's grace, wilderness, intuition, riding, constitution, attack, nature's lore, tracking]],[ [[name]] ] = [[Selandance]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, nature's grace, wilderness, intuition, constitution, attack, nature's lore, tracking]],[ [[name]] ] = [[Theomer]],[ [[area]] ] = [[Edoras]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[intuition, wilderness, coordination, riding, fire building, defense, evasion, agility, nature's lore, awareness]],[ [[name]] ] = [[Leek]],[ [[area]] ] = [[Ethring]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[khuzdul]],[ [[name]] ] = [[Foriolus]],[ [[area]] ] = [[Belegost]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[sindarin]],[ [[name]] ] = [[Bard]],[ [[area]] ] = [[Grey Havens]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[dunael, rohirric]],[ [[name]] ] = [[Elkros]],[ [[area]] ] = [[Adornas]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[silvan, adunaic]],[ [[name]] ] = [[Adric]],[ [[area]] ] = [[Rivendell]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[orcish]],[ [[name]] ] = [[Korthar]],[ [[area]] ] = [[Turseg]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[black]],[ [[name]] ] = [[Messenger]],[ [[area]] ] = [[Azmaroth]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[variag]],[ [[name]] ] = [[Mechant]],[ [[area]] ] = [[Asubuhi]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[haradaic]],[ [[name]] ] = [[Tahirah]],[ [[area]] ] = [[Tarzhayan]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[adunaic]],[ [[name]] ] = [[Scholar]],[ [[area]] ] = [[Outside Azrazayan]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[haradaic]],[ [[name]] ] = [[Tuhyando]],[ [[area]] ] = [[Umbar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[rohirric]],[ [[name]] ] = [[Eodor]],[ [[area]] ] = [[Edoras]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[dunael]],[ [[name]] ] = [[Dervon]],[ [[area]] ] = [[Dale]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[silvan]],[ [[name]] ] = [[Pedhel]],[ [[area]] ] = [[Thranduils]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, assassination, attack, agility, awareness, stalking, aim, lethal precision, deception]],[ [[name]] ] = [[Amidao]],[ [[area]] ] = [[Druwaur]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[tbd]],[ [[name]] ] = [[Tall Tani]],[ [[area]] ] = [[Telshar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, agility, awareness, dodge, aim]],[ [[name]] ] = [[Shara]],[ [[area]] ] = [[Tavorus]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[coordination, constitution, defense, attack, agility, dodge, aim, strength]],[ [[name]] ] = [[Rabban]],[ [[area]] ] = [[Tarzhayan]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[lethal precision, assassination, deception, stalking, intuition]],[ [[name]] ] = [[A large assassin]],[ [[area]] ] = [[Kadar]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[deception]],[ [[name]] ] = [[Ryar]],[ [[area]] ] = [[Southeast of Morgulduin]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[charisma, stalking, coordination, lethal precision, assassination, attack, evasion, deception]],[ [[name]] ] = [[Calad]],[ [[area]] ] = [[Lothlorien]],},
{[ [[affinity]] ] = [[none]],[ [[skills]] ] = [[dodge, stalking, lethal precision, intelligence, assassination, awareness, deception]],[ [[name]] ] = [[Balforth]],[ [[area]] ] = [[Dol Guldur]],},
}