return {{[ [[Misc]] ] = {2},[ [[Armour]] ] = {3},[ [[Healing]] ] = {4},[ [[Bonus]] ] = {5},[ [[Keys]] ] = {6},[ [[Containers]] ] = {7},[ [[Baldrics]] ] = {8},[ [[Weapons]] ] = {9},[ [[Poisons]] ] = {10},[ [[Light]] ] = {11},},
{[1] = {12},[2] = {13},[3] = {14},[4] = {15},[5] = {16},},
{[1] = {17},[2] = {18},[3] = {19},[4] = {20},[5] = {21},[6] = {22},[7] = {23},[8] = {24},[9] = {25},[10] = {26},[11] = {27},[12] = {28},[13] = {29},[14] = {30},[15] = {31},[16] = {32},[17] = {33},[18] = {34},[19] = {35},[20] = {36},[21] = {37},[22] = {38},[23] = {39},[24] = {40},[25] = {41},[26] = {42},[27] = {43},[28] = {44},[29] = {45},[30] = {46},[31] = {47},[32] = {48},[33] = {49},[34] = {50},[35] = {51},[36] = {52},[37] = {53},[38] = {54},[39] = {55},[40] = {56},[41] = {57},[42] = {58},[43] = {59},[44] = {60},},
{[1] = {61},[2] = {62},[3] = {63},[4] = {64},[5] = {65},[6] = {66},[7] = {67},[8] = {68},[9] = {69},[10] = {70},[11] = {71},},
{[1] = {72},[2] = {73},[3] = {74},[4] = {75},[5] = {76},[6] = {77},[7] = {78},[8] = {79},[9] = {80},[10] = {81},[11] = {82},[12] = {83},[13] = {84},[14] = {85},[15] = {86},[16] = {87},[18] = {88},[17] = {89},},
{[1] = {90},[2] = {91},[3] = {92},[4] = {93},[5] = {94},[6] = {95},[7] = {96},[8] = {97},[9] = {98},[10] = {99},[11] = {100},[12] = {101},[13] = {102},[14] = {103},[15] = {104},[16] = {105},[18] = {106},[17] = {107},},
{[1] = {108},[2] = {109},[3] = {110},[4] = {111},[5] = {112},[6] = {113},[7] = {114},[8] = {115},[9] = {116},[10] = {117},[11] = {118},[12] = {119},[13] = {120},[14] = {121},[15] = {122},[16] = {123},[20] = {124},[17] = {125},[21] = {126},[18] = {127},[22] = {128},[19] = {129},},
{[1] = {130},[2] = {131},[3] = {132},[4] = {133},[5] = {134},[6] = {135},[7] = {136},[8] = {137},[9] = {138},[10] = {139},[11] = {140},[12] = {141},[13] = {142},[14] = {143},[15] = {144},[16] = {145},[17] = {146},[18] = {147},[19] = {148},[20] = {149},[21] = {150},[22] = {151},[23] = {152},[24] = {153},[25] = {154},[26] = {155},[27] = {156},[28] = {157},},
{[1] = {158},[2] = {159},[3] = {160},[4] = {161},[5] = {162},[6] = {163},[7] = {164},[8] = {165},[9] = {166},[10] = {167},[11] = {168},[12] = {169},[13] = {170},[14] = {171},[15] = {172},[16] = {173},[17] = {174},[18] = {175},[19] = {176},[20] = {177},[21] = {178},[22] = {179},[23] = {180},[24] = {181},[25] = {182},[26] = {183},[27] = {184},[28] = {185},[29] = {186},[30] = {187},[31] = {188},[32] = {189},[33] = {190},[34] = {191},[35] = {192},[36] = {193},[37] = {194},[38] = {195},[39] = {196},[40] = {197},[41] = {198},[42] = {199},[43] = {200},[44] = {201},[45] = {202},[46] = {203},[47] = {204},[48] = {205},[49] = {206},[50] = {207},[51] = {208},[52] = {209},[53] = {210},[54] = {211},[55] = {212},[56] = {213},[57] = {214},[58] = {215},[59] = {216},},
{[1] = {217},[2] = {218},[3] = {219},},
{[1] = {220},[2] = {221},[3] = {222},[4] = {223},[5] = {224},[6] = {225},[7] = {226},[8] = {227},[9] = {228},[10] = {229},},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A set of climbing gear]],[ [[itemType]] ] = [[misc]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A mining pick]],[ [[itemType]] ] = [[misc]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A jeweled tiara]],[ [[itemType]] ] = [[misc]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Some survival gear]],[ [[itemType]] ] = [[misc]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large mat of moss]],[ [[itemType]] ] = [[misc]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark steel helmet]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An onyx helmet]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A radiant steel helm]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dwarven deathmask]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A tower guard's helmet]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dwarven hauberk]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark mail shirt]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A full suit of etched armour]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A suit of bronze mail]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A finely-shaped pearl carapace]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A radiant mithril shirt]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A suit of sparkling armour]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A suit of light-weight elven chainmail]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A black set of leather and ring mail leggings]],[ [[itemType]] ] = [[legs]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of radiant steel pants]],[ [[itemType]] ] = [[legs]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A shiny set of steel leggings]],[ [[itemType]] ] = [[legs]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of mail pants]],[ [[itemType]] ] = [[legs]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of armoured gauntlets]],[ [[itemType]] ] = [[hands]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Black plate gauntlets]],[ [[itemType]] ] = [[hands]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of radiant steel gauntlets]],[ [[itemType]] ] = [[hands]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of chainmail gloves]],[ [[itemType]] ] = [[hands]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A tarnished tower shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A great tower shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A great war shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dwarven war shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Numiragan, the black targe]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A crystalline shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An emerald shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[itemType]] ] = [[body]],[ [[name]] ] = [[An exquisite set of steel chainmail]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A chainmail vest]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A black ruby shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A superb wall shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Sturdy armour]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The elder's shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Dwarven battlerager armour]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An elven shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A jeweled shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A gold lined shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A skull helmet]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An emerald-encrusted helmet]],[ [[itemType]] ] = [[helmet]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of exquisite chain leggings]],[ [[itemType]] ] = [[legs]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark shield]],[ [[itemType]] ] = [[shield]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A suit of chain link mail]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A hooded chainmail shirt]],[ [[itemType]] ] = [[body]],},
{[ [[command]] ] = [[get red vial from cloak, get red vial from pack, drink vial, put vial in cloak, put vial in pack]],[ [[name]] ] = [[A small red vial]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[get bota from cloak, open bota, 2drink bota, close bota, put bota in cloak]],[ [[name]] ] = [[An elf-skin bota]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[get silver flask from cloak, open flask, 2drink flask, close flask, put flask in cloak]],[ [[name]] ] = [[A silver flask]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[open leather necklace, drink necklace, close necklace]],[ [[name]] ] = [[A leather necklace with vial]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[get steel flask from cloak, open flask, drink flask, close flask, put flask in cloak]],[ [[name]] ] = [[A burnished steel flask]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[get amber vial from cloak, open amber vial, drink amber vial, close amber vial, put amber vial in cloak]],[ [[name]] ] = [[A mysterious amber vial]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[get eye from cloak, get eye from pack, eat eye, put eye in cloak, put eye in pack]],[ [[name]] ] = [[One of Shelob's eyes]],[ [[itemType]] ] = [[packable]],},
{[ [[command]] ] = [[drink cloudy vial, drop empty vial]],[ [[name]] ] = [[A strange, cloudy liquid in a vial]],[ [[itemType]] ] = [[handheld]],},
{[ [[command]] ] = [[drink vial of rejuvenation, drop empty vial]],[ [[name]] ] = [[A vial of rejuvenation]],[ [[itemType]] ] = [[handheld]],},
{[ [[command]] ] = [[drink vial of vigour, drop empty vial]],[ [[name]] ] = [[A vial of vigour]],[ [[itemType]] ] = [[handheld]],},
{[ [[command]] ] = [[chant runes on ring]],[ [[name]] ] = [[A golden ring with a red ruby attached]],[ [[itemType]] ] = [[handheld]],},
{[ [[command]] ] = [[wear gloves from pack]],[ [[name]] ] = [[A pair of dark grey gloves]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[wear bands of slaying from pack]],[ [[name]] ] = [[The bands of slaying]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[get mighty war horn from pack, blow horn, put horn in pack]],[ [[name]] ] = [[A mighty war horn]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[wear boots from pack]],[ [[name]] ] = [[A pair of black boots]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Oromë']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Aulë']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Lórien']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Manwë']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Tulkas']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Ulmo']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink vial, drop empty vial]],[ [[name]] ] = [[A small vial labeled 'Mandos']],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink mixed potion, drop empty vial]],[ [[name]] ] = [[A mixed potion]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[drink phial, drop empty phial]],[ [[name]] ] = [[A phial of Roderick's Dream Potion]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[wear all quartz ring from pack, wear all quartz ring from cloak]],[ [[name]] ] = [[A shimmering silver-quartz ring]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[wear all golden amulet from pack, wear all golden amulet from cloak]],[ [[name]] ] = [[A golden amulet]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pair of weaponsmith gloves]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An emerald brooch]],[ [[itemType]] ] = [[bonus]],},
{[ [[command]] ] = [[wear boots from pack]],[ [[itemType]] ] = [[bonus]],[ [[name]] ] = [[A pair of crocodile-hide boots]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A keyring containing]],[ [[itemType]] ] = [[keyring]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An empty keyring]],[ [[itemType]] ] = [[keyring]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An iron flat key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large, sturdy iron key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A jeweled key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small purple key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small cyan key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small green key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small blue key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small red key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small runed key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A simple iron key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A heavy iron key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An ornate iron key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A very plain key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large, pitted iron key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A wooden key]],[ [[itemType]] ] = [[key]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A leather scout ruck]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An orc hunter's pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An Orc courier pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large, canvas raiding pack of the Corsairs]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dwarven mining pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A camouflaged ruck]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large harvester's pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An iridescent black cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A long shimmering cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A bloodstained cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A charred Morgul guard cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A long black cowled cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A black riding cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A Dol Amroth pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A grey explorer's pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A leather ranger's ruck]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A pelt string]],[ [[itemType]] ] = [[string]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small canvas pack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A courier pack of Barad-dûr]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A backpack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A camouflaged cloak]],[ [[itemType]] ] = [[cloak]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A goblin backpack]],[ [[itemType]] ] = [[pack]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A crude staff sling]],[ [[itemType]] ] = [[sling]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A rugged leather axe belt]],[ [[itemType]] ] = [[belt]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A heavy axe belt]],[ [[itemType]] ] = [[belt]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A leather belt loop]],[ [[itemType]] ] = [[belt]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A simple sheepskin sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A black studded leather baldric]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A studded leather baldric]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A studded green quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An unsightly-looking quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A bloodstained spear sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A woodsman's quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A grey studded sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark leather baldric]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A deerskin sword sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A simple snakeskin sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A supple leather sword sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dagger sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark leather spear sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A green quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An old leather baldric]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large, worn leather quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A black quiver]],[ [[itemType]] ] = [[quiver]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A hefty axe belt]],[ [[itemType]] ] = [[belt]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A spear sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dirty baldric]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small dagger sheath]],[ [[itemType]] ] = [[sheath]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A runed dwarven belt]],[ [[itemType]] ] = [[belt]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A red scabbard]],[ [[itemType]] ] = [[baldric]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A simple metal bootknife]],[ [[itemType]] ] = [[knife]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small knife]],[ [[itemType]] ] = [[knife]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A stubby bootknife]],[ [[itemType]] ] = [[knife]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A wickedly curved knife]],[ [[itemType]] ] = [[knife]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small black-bladed dagger]],[ [[itemType]] ] = [[dagger]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The twilight dagger]],[ [[itemType]] ] = [[dagger]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A beautiful, deadly sword forged by]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Catalamir's Vengeance - Soul Tainter]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark steel longsword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A great bone-handled flamberge]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A longsword of ruin]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A double-bladed staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A walking staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A strange runed staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The ice staff of Ulkhalad]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A bladed staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Carack-Amarth, the axe of doom]],[ [[itemType]] ] = [[axe]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A jade trident]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A long spear]],[ [[itemType]] ] = [[spear]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A fearsome-looking longbow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A reinforced great war bow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark crimson longbow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A great elven war-bow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A wicked looking flail]],[ [[itemType]] ] = [[flail]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Gabilinbar, the dwarven warhammer]],[ [[itemType]] ] = [[hammer]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[Abarada, Breaker of Beasts]],[ [[itemType]] ] = [[prod]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A large training prod]],[ [[itemType]] ] = [[prod]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The Globe of Protection]],[ [[itemType]] ] = [[globe]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A handcrafted arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A silver arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An elven arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The bone sword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An enchanted black staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A steel-tipped arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A simple arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A woodsman's arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A strange grey sword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An archaic longsword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A sturdy wooden arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A red sword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An ivory tulwar]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A slender black arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A beautiful silvan longsword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A great iron axe]],[ [[itemType]] ] = [[axe]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A crudely-made bow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[An impeccable hammer]],[ [[itemType]] ] = [[hammer]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dragon longsword]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A fine silver arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A brutal-looking dwarven axe]],[ [[itemType]] ] = [[axe]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A living staff]],[ [[itemType]] ] = [[staff]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A beautiful longsword of elven make]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A menacing spiked mace]],[ [[itemType]] ] = [[mace]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A clawed arrow]],[ [[itemType]] ] = [[arrow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A nicely curved dagger]],[ [[itemType]] ] = [[dagger]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A dark runed battle axe]],[ [[itemType]] ] = [[axe]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A straight knife]],[ [[itemType]] ] = [[knife]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[The serpent's tongue]],[ [[itemType]] ] = [[sword]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A magnificent longbow]],[ [[itemType]] ] = [[bow]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A vial of nightshade poison]],[ [[itemType]] ] = [[poison]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[a sac of viscous poison]],[ [[itemType]] ] = [[poison]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A small vial of belladonna poison]],[ [[itemType]] ] = [[poison]],},
{[ [[command]] ] = [[wear all light ring from pack,wear all light ring from cloak]],[ [[name]] ] = [[A smoothly polished white ring]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A glowing silver bracelet]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[]],[ [[name]] ] = [[A long shimmering cloak]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[light crystal]],[ [[name]] ] = [[A crystal in the shape of the Eye]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[light torch]],[ [[name]] ] = [[A torch]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[light brand]],[ [[name]] ] = [[A brand]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[light brand]],[ [[name]] ] = [[A crystal]],[ [[itemType]] ] = [[light]],},
{[ [[command]] ] = [[wear all dark ring from cloak, wear all dark ring from pack]],[ [[name]] ] = [[An ominous dark ring]],[ [[itemType]] ] = [[dark]],},
{[ [[command]] ] = [[detach gem]],[ [[name]] ] = [[A simple-looking necklace]],[ [[itemType]] ] = [[dark]],},
{[ [[command]] ] = [[raise hood]],[ [[name]] ] = [[A crimson cloak]],[ [[itemType]] ] = [[dark]],},
}